AA-2821-Add-Work-with-ApplyBoard-module-v1
ApplyBoard/applyassist-theme pull request #53
Opened 2021-04-28 11:47 UTC by ShiraziElham

To Validate [AA-2821](https://applyboard.atlassian.net/browse/AA-2821) :

2021-04-28 11:56 UTC, wesleymartin-ab requested changes
I highlighted some picky changes, but only because I can tell you for sure that that Jude will point out these changes anyways.

2021-04-28 11:56 UTC, wesleymartin-ab commented on templates/home_page.hbs
> +  <div id="work_with_AB_module" class="clearfix container-inner knowledge-base">
Somehow this DIV will need to fill the entire width of the page

2021-04-28 11:56 UTC, wesleymartin-ab commented on templates/home_page.hbs
> +              <a class="btn btn--primary--inverse" style="width:-webkit-fill-available"; aria-label="Students" href="https://www.applyboard.com/services/students" role="button">
These buttons should all either have transparent backgrounds, or have backgrounds matching the background of the main div

2021-04-28 11:56 UTC, wesleymartin-ab commented on templates/home_page.hbs
> +      <div class="column column--sm-6 section-list-item" align="center" style="padding-top:150px">
This whole section should be a little higher up, or the image should be a littler smaller (see above)

2021-04-28 11:56 UTC, wesleymartin-ab commented on templates/home_page.hbs
> +      <div id="image_frame" class="column column--sm-6 section-list-item" align="center">
This image should have more blue space around it. Once you have the blue area stretching the whole width of the page, you will also need to either increase the height of the main blue div, or you will need to make the image a little smaller

2021-04-29 14:39 UTC, ShiraziElham commented
@wesleymartin-ab You are ALL right. I checked this one with our client to get his expectation level and I got it ALL. The modification are in place and checked with Jude. He was not comfortable with how my screen was showing the design so it may change again later. But this is what he verified based on what he could see. Please review again.

2021-04-29 14:50 UTC, wesleymartin-ab requested changes
These buttons should be that dark blue when you mouse over them
https://user-images.githubusercontent.com/64908463/116570945-a637a900-a8d8-11eb-9237-e0117f4e3787.mov

2021-04-29 19:22 UTC, wesleymartin-ab approved these changes

2021-04-29 20:02 UTC, merged